name: idcard
description: Application like a ID card, where user can write and save own data in one place.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.5
  shared_preferences: ^0.5.6
  path_provider: ^1.6.5
  flushbar: ^1.10.0
  file_picker: ^1.9.0+1
  cloud_firestore: ^0.13.5
  provider: ^4.1.0
  firebase_auth: ^0.16.0
  flutter_spinkit: ^4.1.2
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.16



  url_launcher: ^5.4.5
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
  - images/



  fonts:

    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf

    - family: Handlee
      fonts:
        - asset: fonts/Handlee-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf

    - family: JustAnotherHand
      fonts:
        - asset: fonts/JustAnotherHand-Regular.ttf

    - family: PatrickHandSC
      fonts:
        - asset: fonts/PatrickHandSC-Regular.ttf

    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf

    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf

    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf

    - family: Sacramento
      fonts:
        - asset: fonts/Sacramento-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: FredokaOne
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf

    - family: SociaIcons
      fonts:
        - asset: fonts/SociaIcons.ttf
